Repository big-neon/bn-web, pull requests merged in 2019-05, with the labels that each got.

#1399 Check for 0 on Promocodes Report
  src/components/pages/admin/reports/eventPromoCode/EventPromoCodeTable.js
  src/stores/reports/promoCodeReport.js
Labels: in progress

#1400 Preload key requests
  public/index.html
Labels: in progress

#1401 Add font-display to specify how fonts are shown before they are loaded
  public/index.html
  public/style.css
Labels: in progress

#1404 Fixed the sh if statement
  scripts/build_prod.sh
Labels: in progress

#1403 Organization Report -> TDR -> Source / Platform fields
  src/components/pages/admin/reports/transactions/TransactionRow.js
  src/components/pages/admin/reports/transactions/Transactions.js
Labels: in progress

#1411 Event Create: select venue if only one exists
  src/components/pages/admin/events/updateSections/Details.js
Labels: in progress

#1415 Event Create: Auto select venue if only 1 private available
  src/components/pages/admin/events/updateSections/Details.js
Labels: in progress

#1420 Factored in credit card fee item type.
  src/components/pages/orders/Order.js
Labels: in progress

#1413 Fix status and quantities
  src/components/pages/admin/events/dashboard/holds/children/List.js
Labels: in progress

#1412 Add email, phone and order id to search
  src/components/pages/admin/events/dashboard/refunds/Refunds.js
Labels: in progress

#1398 Box office user access
  src/components/elements/header/RightUserMenu.js
  src/components/pages/admin/events/EventSummaryCard.js
  src/stores/user.js
Labels: in progress

#1422 Fixed text overflow
  src/components/pages/boxoffice/guests/GuestRow.js
Labels: in progress

#1421 Commented out 'Price at door' for now
  src/components/pages/admin/events/updateSections/TicketType.js
Labels: in progress

#1428 Update NPM package
  ui-tests/package-lock.json
  ui-tests/package.json
Labels: in progress

#1426 Danijel#1392 pagination rework
  src/components/elements/Pagination.js.old
  src/components/elements/pagination/MiddleSpace.js
  src/components/elements/pagination/NumberBlock.js
  src/components/elements/pagination/index.js
  src/components/pages/admin/fans/Index.js
  src/components/pages/admin/reports/transactions/Transactions.js
Labels: in progress

#1427 Reduce moment filesize
  config/webpack.config.prod.js
  package-lock.json
  package.json
Labels: in progress

#1442 Fix issue with download CSV and large datasets
  src/helpers/downloadCSV.js
Labels: Client Reported, in progress

#1433 Danijel#1257 search component
  src/components/elements/SearchBox.js
  src/components/pages/admin/reports/transactions/Transactions.js
Labels: in progress

#1469 Fix issue with CSV export including invalid row
  src/helpers/downloadCSV.js
Labels: bug

#1440 Name comp buttons on holds
  src/components/elements/ColorTag.js
  src/components/pages/admin/events/dashboard/holds/HoldRow.js
  src/components/pages/admin/events/dashboard/holds/List.js
  src/components/pages/admin/events/dashboard/holds/children/ChildDialog.js
  src/components/pages/admin/events/dashboard/holds/children/ChildRow.js
  src/components/pages/admin/events/dashboard/holds/children/List.js
Labels: in progress

#1478 Search guest list by full name
  src/components/pages/boxoffice/guests/Index.js
Labels: in progress

#1472 [DNM] Fix multiple row issue for report
  src/components/pages/admin/reports/eventSummaryAudit/SummaryAudit.js
Labels: in progress

#1476 DNM - Org member created artists are private, hide edit link for public artists
  src/components/pages/admin/artists/Artist.js
  src/components/pages/admin/artists/List.js
  src/components/pages/admin/venues/Venue.js
Labels: in progress

#1494 PR Template: Switch closes to references for QA flow
  .github/pull_request_template.md
Labels: in progress
